### ISSUE TITLE
C# Track courses to be completed

### ISSUE THREAD

**Issue by freeCodeCamperMaryna** [freeCodeCamperMaryna/Treehouse#2]
## TODO

* Courses left to complete the Treehouse C# Track
* [ ] Usig GitHub with Visual Studio
* [ ] C# Collection
* [ ] Querying With LINQ
* [ ] Package Management with NuGet
* [ ] Exercises for each video
:tada: :ok_woman:
